deployment:
  tasks:
    - export DEPLOYPATH=/home/ikiz7975/public_html
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .env.production $DEPLOYPATH/.env
    - /bin/mkdir $DEPLOYPATH/storage
    - /bin/mkdir $DEPLOYPATH/storage/app
    - /bin/mkdir $DEPLOYPATH/storage/framework
    - /bin/mkdir $DEPLOYPATH/storage/framework/cache
    - /bin/mkdir $DEPLOYPATH/storage/framework/sessions
    - /bin/mkdir $DEPLOYPATH/storage/framework/views
    - /bin/mkdir $DEPLOYPATH/storage/logs
    - /bin/chmod -R 755 $DEPLOYPATH/storage
    - /bin/chown -R username:username $DEPLOYPATH